### ISSUE TITLE
Create panel with pending request

### ISSUE THREAD

**Issue by rperez89** [1Hive/token-request-app#29]
We ran into several issues trying to create the request and finalizing it in only one action as we need more than one transaction.
So talking with sohkai and @willjgriff we realized that in order to finalize the token request first we need the first transaction to be mined.

So thinking a good way to do that with a nice UX what we can do is the following,

have a pending transactions side-panel with a button that has a count of pending tx's on it that blinks when new ones are added. So that way once the request is created and mined the user will see that has a pending action to do (finalize the  request)

That is also aligned with what brett suggested : 

" You can block the user after they've signed the first transaction with a loader, and then in the background script wait until you get the `TokenRequestCreated` event and push that through to the frontend

Once the frontend gets the latest `TokenRequestCreated` event that it was expecting, it can immediately open the intent for the next transaction
But doing this well is going to be a bit complicated because the user might leave the app and come back (so you'll probably want a queue of "pending token requests" in the UI somewhere, that they can trigger themselves) "

**Comment by lkngtn** [comment]
I think the approach of showing multiple transactions in a progress bar of some sort makes sense, this is sort of the approach that is taken with onboarding. 

<img width="248" alt="image" src="https://user-images.githubusercontent.com/4986634/63172950-d2c86600-c00c-11e9-88a1-32440c497c2c.png">

We would probably want something much more compact in the signer panel. 

Ultimately this is pretty painful for the user (so many clicks), and could problably be improved in subsequent versions of aragonOS via meta-transactions. In which the case we might be able to do something like have the user sign a single blob with the full intent, then have a relayer unpack that and send transactions in sequence waiting for confirmation.

**Comment by rperez89** [comment]
But if you have more than one request pending ? How can we show múltiple request with that indicator

**Comment by lkngtn** [comment]
So lets say you have 2 transactions the user needs to sign, we can tell them in the beginning that they will need to sign two actions to complete the flow. The progress bar would start at 0% (0/2), jump to 50% (1/2), and then jump to 100% (2/2) when all have been completed?

**Comment by willjgriff** [comment]
> have the user sign a single blob with the full intent, then have a relayer unpack that and send transactions in sequence waiting for confirmation.

The issue is we need to wait until the first transaction is confirmed to determine what the `TokenRequestId` is which is input to the second transaction, so they can't both be signed at once.

> So lets say you have 2 transactions the user needs to sign, we can tell them in the beginning that they will need to sign two actions to complete the flow. The progress bar would start at 0% (0/2), jump to 50% (1/2), and then jump to 100% (2/2) when all have been completed?

Correct me if I'm wrong but I think what @rperez89 is referring too is what if someone submits 2 `TokenRequests` before submitting `finalise()` on either, then they have 2 `finalise()` calls to be made. Where do we display these?

The process you suggest will be useful for a single flow, but if a flow is interrupted, eg a user has deposited funds but leaves the app and comes back to it, there needs to be a way to finish it.

**Comment by rperez89** [comment]
not needed anymore
