### ISSUE TITLE
Token Request App

### ISSUE THREAD

**Issue by yeqbfgxjiq** [1Hive/token-request-app#4]
The Token Request app allows Aragon organizations to allow users to propose minting tokens in exchange for depositing tokens into the organizations vault. 
- Status: not currently under development, but there is [a repo for it](https://github.com/1Hive/token-request-app)

@lkngtn and @burrrata shared lots of thoughts on this [here](https://github.com/1Hive/ideas/issues/3) and [here](https://github.com/1Hive/website/issues/17). 
TL;DR: @burrrata says yes and @lkngtn says maybe.

@0xGabi said: "This app is really important to allow donations. I think is a must in the proposal"

<br>

It sounds like we generally think it's useful, but it's not as important as the [Redemptions App](#1 ). Is that about accurate?

**Comment by lkngtn** [comment]
I've updated the readme in this repo, to more clearly define the requirements.

**Comment by lkngtn** [comment]
Going to close this now that the readme has the requirements, and we have #6 for estimating time.
