### ISSUE TITLE
Initial Impressions: UI

### ISSUE THREAD

**Issue by yeqbfgxjiq** [1Hive/token-request-app#51]
### Purposefully avoiding reading the directions first to give feedback on first impressions and the UI

Opened up the app, synced up the devchain to metamask, and requested a token. The window that opened up presented some options, but I have no idea what they are for or why. Since (I think) I want TST tokens I selected that. 

But then there's 2 amount boxes. Why are there 2 amount boxes? It would be great if I could just input the amount of tokens I want to offer as tribute and then get a fixed amount of DAO tokens back. Having every potential new member of the DAO name their own price seems problematic. 

Now that I think about it though... in the top of the sidebar am I selecting the token I want to receive or the token I want to request? Much confuse.

Furthermore, after clicking around with multiple combinations the "submit request" button isn't clicking. The template built and everything looks good, but I can't click stuff to actually try it out. 

<br>

### Suggestions for improvement

~~Get the "submit request" button working.~~
- ~~Since I'm a sample size of 1 this might be a bug/error on my end. Is anyone else having this issue?~~

Fixed! Thanks @rperez89 :)

This might be a stretch... but would it be possible to have a Uniswap like interface where the request happens more like a trade and less like, well, less like an unfamiliar pattern that users are unfamiliar with? 
- The more I think about it the more I like this. There could be 2 big buttons (or menus) in the center of the app for requesting or withdrawing). The user could then select the parameters they want in the main window of the app and the sidebar would simply display the information of the parameters selected with a button to "submit request". The Metamask actually asks the users to sign the transactions.

**Comment by lkngtn** [comment]
> But then there's 2 amount boxes. Why are there 2 amount boxes? It would be great if I could just input the amount of tokens I want to offer as tribute and then get a fixed amount of DAO tokens back.

Im not sure I follow, where would the exchange rate come from?

**Comment by yeqbfgxjiq** [comment]
The exchange rate would come from the DAO itself. Like in MolochDAO 1 ETH = 1 DAO token.

If everyone names their own price then the DAO members have to create a valuation model on every new member, come to consensus on the fair exchange rate, vote on it, etc... it's a whole thing...

**Comment by rperez89** [comment]
The way we think it was you need to select the token that you are offering as a tribute, the amount and the org token amount that you want. We are not showing a combo box for the token requested because it only can be the org token. Maybe @lkngtn can help me here...




> The exchange rate would come from the DAO itself. Like in MolochDAO 1 ETH = 1 DAO token.
> 
> If everyone names their own price then the DAO members have to create a valuation model on every new member, come to consensus on the fair exchange rate, vote on it, etc... it's a whole thing...

And about this... i think that that is how we all think that should be the workflow, you offer a tribute  amount and request X number of org token and then a vote is submitted

**Comment by yeqbfgxjiq** [comment]
@rperez89 

> We are not showing a combo box for the token requested because it only can be the org token

Currently it shows both ETH and the org token. Are we going to remove ETH as an option?

If there are going to be multiple tokens that can be requested, maybe then we should just show a little text box in the side bar explaining this in more detail? There already is a little explanation about the "pretransaction" stuff, so maybe we could just add a line that says "if you want X token select that and then offer your tribute" or whatever?

<br>

> And about this... i think that that is how we all think that should be the workflow, you offer a tribute amount and request X number of org token and then a vote is submitted

I don't follow. Are you saying that we want it like MolochDAO where it's 1token for 1token, or that we want every user to name their own price. The later feels like it would become a headache

**Comment by yeqbfgxjiq** [comment]
### Second Impressions! 

It works! Yay :)

The current user flow is a bit confusing because requesting a token requires 2 actions:
- click the "New Request" button and create a request
- click the small little "Actions" drop down menu to "submit" the request we just created

This is confusing because the "New Request" button is big and blue, indicating that it's a main action. After that I thought I was done since the request shows as pending. The "Actions" button is small and this made me think that it was a minor thing, not something required to actually submit the request. 
@rperez89 explained this is because permissions could be set up so that *only* DAO members could submit requests to be voted on, but anyone could make requests. Permissions could also be set in a DIY fashion where the user does it all. 
- IF the DAO members are responsible for this the UI is acceptable because it is expected that DAO members would know how their own DAO works. 
- IF users are responsible for this 2 step process, then it needs to be made clear what the next action is after creating a request. This could be a text box that appears in the main window prompting the user to submit the request they just created. If the user has already submitted a request, then the text box could explain that they can withdraw the request if they want. This might actually be a good thing to add in general because people often get confused. @rperez89 would this be an easy thing to add into the UI?

**Comment by rperez89** [comment]
> ### Second Impressions!
> It works! Yay :)
> 
> The current user flow is a bit confusing because requesting a token requires 2 actions:
> 
> * click the "New Request" button and create a request
> * click the small little "Actions" drop down menu to "submit" the request we just created
> 
> This is confusing because the "New Request" button is big and blue, indicating that it's a main action. After that I thought I was done since the request shows as pending. The "Actions" button is small and this made me think that it was a minor thing, not something required to actually submit the request.
> @rperez89 explained this is because permissions could be set up so that _only_ DAO members could submit requests to be voted on, but anyone could make requests. Permissions could also be set in a DIY fashion where the user does it all.
> 
> * IF the DAO members are responsible for this the UI is acceptable because it is expected that DAO members would know how their own DAO works.
> * IF users are responsible for this 2 step process, then it needs to be made clear what the next action is after creating a request. This could be a text box that appears in the main window prompting the user to submit the request they just created. If the user has already submitted a request, then the text box could explain that they can withdraw the request if they want. This might actually be a good thing to add in general because people often get confused. @rperez89 would this be an easy thing to add into the UI?

yes for sure we can add info for the user!

**Comment by lkngtn** [comment]
> The way we think it was you need to select the token that you are offering as a tribute, the amount and the org token amount that you want. We are not showing a combo box for the token requested because it only can be the org token. Maybe @lkngtn can help me here...

I went through the process and did find it a bit confusing what token I was selecting, I think it would be much clearer if we put the requested token inline with the amount sort of like in the fundraising app: 

<img width="435" alt="image" src="https://user-images.githubusercontent.com/4986634/65003801-062a3900-d8c8-11e9-8fd0-513032b84e9b.png">

I would also recommend changing the header from just `amount` to `offered amount`

If we want we can also display the Org token inline in the same way (but not have the drop down enabled to indicate that it static).
