### ISSUE TITLE
Requests and My Requests tabs are the same

### ISSUE THREAD

**Issue by yeqbfgxjiq** [1Hive/token-request-app#59]
![1](https://user-images.githubusercontent.com/42473928/65296696-3f1a1600-db33-11e9-8ce1-b92d304a83c8.png)
![2](https://user-images.githubusercontent.com/42473928/65296699-40e3d980-db33-11e9-9bee-cdf704ed64a5.png)

Both tabs show the same data. This was the case after the initial request, after submitting the request, and after approving the request.

Why are there 2 different tabs?

**Comment by lkngtn** [comment]
try viewing from a different account?

They SHOULD be the same if there is only one request and its one you made, since the purpose of the tabs is to show all, and show only yours. 

I just tested and it seems to work correctly for me.
