### ISSUE TITLE
Estimate time

### ISSUE THREAD

**Issue by lkngtn** [1Hive/token-request-app#6]
Before applying for a grant we should estimate the time requirement and resource availability to complete this.

**Comment by lkngtn** [comment]
@willjgriff @0xGabi @rperez89 @fabriziovigevani 

I've updated the [readme](https://github.com/1Hive/token-request-app) with more formal requirements. Please let me know if it is clear or if you have any questions about how the app would work. 

I think there is some complexity that may make this a bit more difficult to implement from on the contract side than the redemptions app. Specifically the when a user makes a request they must send the payment tokens to the token-request app and the token request app must create a vote in the voting app. If the vote passes it should trigger a function on the request-tokens app to move the users payment tokens into the vault and mint the requested tokens for the user. But if it fails the vote will not be able to send any additional action. The user will need to come back to the token request app and claim their payment tokens after the vote has failed, and the trickiest part may be that the token request app will need to keep track of the vote id when creating the vote in order to validate that the vote has completed and was rejected.

**Comment by 0xGabi** [comment]
With @rperez89, @fabriziovigevani and me. We estimate:

Write Smart Contracts: **40hs**
Write Smart Contracts Test: **20hs**
Front-end: **60hs**

We also been thinking that we might need to have an exchange rate protected behind a role (https://github.com/1Hive/token-request-app/issues/1)

**Comment by lkngtn** [comment]
Great! 

Can you explain the reasoning behind the exchange rate?

**Comment by rperez89** [comment]
@lkngtn i.e with 1 DAI you always  get 100 honey? or is that something configurable by parameters?

**Comment by lkngtn** [comment]
Ah for this use case I think each request should be for a variable amount of tokens but require a vote. 

The reason being that it becomes possible for someone to submit a request for tokens but at bellow market rate, on the basis that they have either already done work for the org or are proposing to do work. This is actually a key part of how moloch works, since you just have one proposal type, people who provide work request tokens at a bellow market rate. 

If you have the exchange rate you cannot really do this. It may make sense in the context of a fundraising app where you don't want participation in the organization to be permissioned by a vote-- but I think the apiary/fundraising app addresses this use case already fairly well.

**Comment by lkngtn** [comment]
Another way to think about this permissioned structure is sort of like how founders would allocate equity to investors. There would be a negotiation based on what the investors/founders are each bringing to the table.

**Comment by lkngtn** [comment]
I think this can be closed at this point.
