### ISSUE TITLE
ETH is not able to be included with addToken function

### ISSUE THREAD

**Issue by 0xGabi** [1Hive/token-request-app#60]
If ETH is not include on initialization is not able to be included later cause in [this line](https://github.com/1Hive/token-request-app/blob/master/contracts/TokenRequest.sol#L98) we check that the address pass as parameter is contract and in case of passing the ZERO_ADDRESS this always fails

**Comment by fabriziovigevani** [comment]
We have to check if the address is ETH then don't require that the address is a contract.

Also probably related, we can't assume that ETH is going to always be in the list, so we should check in the background script if it's actually added in the contract.
