### ISSUE TITLE
Update Radspec upstream to support multiple return values

### ISSUE THREAD

**Issue by lkngtn** [1Hive/token-request-app#62]
We need to be able to display multiple return values eg ("Mint x tokens to y address in exchange for z dai")

**Comment by onbjerg** [comment]
Can be closed when/if https://github.com/aragon/radspec/pull/79 is merged.

**Comment by rperez89** [comment]
We are still waiting for this to be merged, as sohkai is reviewing it i will move it to the next sprint just to keep an eye over the PR

**Comment by rperez89** [comment]
Moving to next sprint as it was not merged yet

**Comment by onbjerg** [comment]
Merged
