### ISSUE TITLE
Error: ENS name not defined

### ISSUE THREAD

**Issue by RuneOrion** [1Hive/token-request-app#67]
I tried deploying the app to the Rinkeby network by following the commands:

`dao install <dao-address> token-request.open.aragonpm.eth --app-init-args <vault-address> <token-manager-address>`

But the `token-request.open.aragonpm.eth` for rinkeby seems to not work and gives me an `ENS name not defined` error.

And so I changed  `token-request-staging.open.aragonpm.eth` and managed to get pass the `ENS name not defined` error but ends up with an `Invalid initialisation params for app` and `Cannot read property 'replace' of undefined`

Is token-request deployed on Rinkeby network yet?

**Comment by 0xGabi** [comment]
Hey @RuneOrion the `token-request` app as well as the `time-lock` were deployed to staging while we keep testing them. You can instal with the repo name `token-request-staging.open.aragonpm.eth`

**Comment by RuneOrion** [comment]
Thanks @0xGabi. Okay using staging seems to be able allow me to dao install it. May I know when it will pass staging? Also may suggest that this issue can be closed. I also have another issue #68.
