### ISSUE TITLE
Initialisation with Agent does not make tokens show up in Finance

### ISSUE THREAD

**Issue by RuneOrion** [1Hive/token-request-app#68]
I have taken the initiative to deploy `token-request-staging.open.aragonpm.eth`. For initialisation, I used the `agent` instance, and managed to do a token-request. But I had to do a trial-and-error for the permissions. May I know if I have set permissions I need to activate for staging properly?

Also, I managed to do a successful token request, but the token ends up in the agent and does not show up in the Finance tab. This is the transaction https://rinkeby.etherscan.io/tx/0x78610ff5f11e1d087614e55922cb66db3f1761f93ad1f8685365030c032d68a4 but does not show up in Finance tab. In order for it to show up, I need to use Agent to deposit into finance itself (which is an extra step). Is this normal behaviour? or did I configure something wrong?

My rinkeby deployment can be found here using the staging : https://rinkeby.aragon.org/#/v1adl/0x9077a49dd48475c9969f7b2c42096899b3b72443

**Comment by RuneOrion** [comment]
Actually, as I used Token Request for the 2nd time, the token starts to add up automatically on Finance without me doing the extra step of depositing into Finance itself. Now I'm confused.

**Comment by lkngtn** [comment]
Hi @RuneOrion 

Sorry for the delayed reply, and cool to see people playing around with the token request app!

As far as I'm aware, the issue you are describing is the normal behavior for the finance app at this time. In order for  a token to be tracked by finance there must have been atleast one deposit for that token contract (from any address). Once that first deposit is made the finance app knows watch that token contract for balance updates. 

There is a relevant issue for finance here https://github.com/aragon/aragon/issues/776
