### ISSUE TITLE
Select an acceptable payment token by default

### ISSUE THREAD

**Issue by lkngtn** [1Hive/token-request-app#75]
Currently the default is simply "token", which forces the user to understand that there is a selection to be made and make a selection before proceeding. Many orgs will only have a single token they are accepting, and so it would be better UX to simply select the first acceptable token by default. (if there is is only one token we can even make this not a drop down), if it there is more than one we can use the first in the list and have the drop down allow them to select a different one. 

<img width="444" alt="image" src="https://user-images.githubusercontent.com/4986634/67334761-af300900-f4f0-11e9-93f0-b335b4ea184c.png">

**Comment by rperez89** [comment]
closed via #85
