### ISSUE TITLE
Show amounts with more precision inline

### ISSUE THREAD

**Issue by lkngtn** [1Hive/token-request-app#76]
Currently we only show hole amounts, 0.1 ETH is shown as 0 ETH for example. We should provide atleast 3 units of precision for all numbers (eg if 100, or 0.01), and we should somehow allow people to expand this view to see the actual amount if it has been rounded. 

<img width="247" alt="image" src="https://user-images.githubusercontent.com/4986634/67337011-55c9d900-f4f4-11e9-9d13-3255e4c65191.png">

**Comment by rperez89** [comment]
closed via #85
